version: '3.7'

x-laravel-env: &laravel-env
    APP_NAME: "Primex API"
    APP_ENV: "development"
    APP_KEY: "+83gWjsQKpScFDGt5cLl7eCMO02gsWqa4NFwIbDKrtU="
    APP_DEBUG: "true"
    DB_HOST: "mysql"
    DB_DATABASE: "primex"
    DB_USERNAME: "root"
    DB_PASSWORD: "root"
    LOG_CHANNEL: "daily"
    QUEUE_CONNECTION: "sync"
    REDIS_HOST: "redis"

services:
    server:
        build:
          context: .
          target: environment
        command: ['./artisan', 'serve', '--port', '80', '--host', '0.0.0.0', '--no-reload']
        networks:
          development-stack:
            aliases:
                - service.primex-api.v1.docker
        volumes:
          - ./src:/srv/application
        environment:
          <<: *laravel-env

    composer:
        image: ericgaonz/laravel:1.0
        entrypoint: ['composer']
        working_dir: /container/application
        volumes:
            - composer-data:/root/.composer/
            - ./src:/container/application
        environment:
            - APP_ENV=development

    artisan:
        image: ericgaonz/laravel:1.0
        init: true
        entrypoint: ['php', 'artisan']
        working_dir: /container/application
        volumes:
            - ./src:/container/application
        networks:
            development-stack:
        environment:
            <<: *laravel-env

    test:
        image: ericgaonz/laravel:1.0
        entrypoint: ['php', './vendor/bin/phpunit']
        working_dir: /container/application
        volumes:
            - ./src:/container/application
        networks:
            development-stack:

networks:
    development-stack:
        external:
            name: ${DEVELOPMENT_STACK_NETWORK:-devstack_default}

volumes:
    composer-data:
